### ISSUE TITLE
PA mirror-copy is broken in claimed buildrooms

### ISSUE THREAD

**Issue by AtlasTheProto** [Bkamahl/ReservableRooms#1]
Attempting to duplicate a prop with PA mirror does not work as expected, prop is not duplicated, regular mirror functionality still works though as that just moves the prop.

**Comment by Bkamahl** [comment]
Solved in update [V10](https://github.com/Bkamahl/ReservableRooms/commit/054ddedfa92aae05f5199f8fd370746a15c11e00)

**Comment by Bkamahl** [comment]
resolved #1

**Comment by Bkamahl** [comment]
resolved #1
